name: jupyter
channels:
- conda-forge
dependencies:
- python=3.10
- jupyterlab 
- jupyterlab-git
- jupyterlab-drawio
- jupyterlab-github
- jupyterhub
- ipywidgets
- ipyleaflet
- tensorboard
- nodejs
- pip
- mamba_gator
- pip:
  - jupyterlab-tensorboard-pro