on:
  push:
    branches:
      - 'master'
    paths:
      - 'kali-desktop/**'
      - '.github/workflows/kali-desktop.yml'
    schedule:
      - cron: "0 0 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/kali-desktop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push desktop based on base kali Docker image
        uses: docker/build-push-action@v2
        with:
          context: kali-desktop
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:kali-linux-core
          build-args: |
            BASE_IMAGE=ghcr.io/xtruder/kali-base:latest

      - name: Build and push desktop based on default kali Docker image
        uses: docker/build-push-action@v2
        with:
          context: kali-desktop
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:kali-linux-default
          build-args: |
            BASE_IMAGE=ghcr.io/xtruder/kali-default:latest
